### ISSUE TITLE
[FEAT] FastAPI project init

### ISSUE THREAD

**Issue by whthdbs03** [beom-jo-city/catch_mind_server#1]
## Background
- FastAPI를 사용하여 catch mind 벡엔드 관리

## Todo
- [x] 리더보드에서 상위 10개의 점수를 반환하는 API.
- [x] 닉네임과 스코어를 저장하는 API
- [x] 이미지 데이터를 받아서 모델 예측 결과를 받아오는 API
